### ISSUE TITLE
Extra db GRANT for 127.0.0.1 not added when migrating site

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/provision#2]
After upgrading Barracuda and Octopus to BOA-2.2.1, ecee14360646b01ae76d8d1413696528cd53cd75 does not appear to add the extra db GRANT for 127.0.0.1 when migrating a site.  Only the standard localhost / db_user entries are present in the mysql.user table. 

Also, it would make sense to add the IPv6 equivalent ::1 to the extra GRANTS as well.

**Comment by omega8cc** [comment]
Right, we have fixed this in https://github.com/omega8cc/provision/commit/2e90dffe65762aaa87160ee368812ae5c7c8d6d4

**Comment by omega8cc** [comment]
I mean, fixed minus IPv6 thing, see: https://drupal.org/node/2241805

**Comment by pricejn2** [comment]
Good deal.  Thanks again.
