### ISSUE TITLE
Exclude private/temp from backup set

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/provision#3]
I haven't completely investigated what (if any) temp files are excluded from a provision backup set, but I know that sites/example.com/private/temp is included.  If temp files are typically excluded, then private/temp should be added to that exclusion list.

**Comment by omega8cc** [comment]
Aegir doesn't exclude anything from backups it creates.

**Comment by pricejn2** [comment]
Gotcha, thanks.  I'll leave a reference to https://drupal.org/node/1484214 and close this out.
